### ISSUE TITLE
Full city name not always displays correctly

### ISSUE THREAD

**Issue by xxczaki** [xxczaki/open-weather-cli#1]
For example, when you type `$ weather -l New York`, the output will be:
```
New

Temperature: 12 Celsius
--------
Pressure: 1003 HPa
Humidity: 93 %
Cloudiness: 90 %
Wind speed: 1.5 km/h
```
I don't know what to do :cry:

**Comment by kirkins** [comment]
I've had this problem with other bash programs too.

You could do:

    weather -l New\ York

Or:

    weather -l "New York"

**Comment by xxczaki** [comment]
@kirkins Thank you! :smile:
